export interface Country{
    id : number,
    name:string,
    iso3:string,
    iso2:string,
    phone_code:string,
    capital:string,
    currency:string,
    currency_symbol:string,
    tld:string,
    native:string,
    region:string,
    subregion:string,
    latitude:string,
    longitude:string,
    emoji:string,
    emojiu:string,
}